// You are given two strings s and t.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:

// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
// Example 2:

// Input: s = "", t = "y"
// Output: "y"

// Constraints:

// 0 <= s.length <= 1000
// t.length == s.length + 1
// s and t consist of lowercase English letters.

#include <bits/stdc++.h>
using namespace std;

char findDifference(string s, string t)
{
  int n = s.size();
  int m = t.size();
  char ans;
  unordered_map<char, int> mpp; // store <char,frequency>
  // first we traversal t string because it has extra char
  for (int i = 0; i < m; i++)
  {
    mpp[t[i]]++;
  }
  for (int i = 0; i < n; i++)
  {
    mpp[s[i]]--;
  }
  for (auto it : mpp)
  {
    // for extra char
    if (it.second == 1)
      ans = it.first;
  }
  return ans;
}

int main()
{
  string s, t;
  cin >> s >> t;
  char answer = findDifference(s, t);
  cout << answer << endl;
  return 0;
}